### ISSUE TITLE
OSC/UDP commands on PI

### ISSUE THREAD

**Issue by deadbutalive** [dividuum/info-beamer#32]
I'm having trouble receiving OSC on raspberry pi 2 v0.9.4.  The short version is I'm trying to send a next command via OSC for the video playlist.  Any guidance is appreciated

**Comment by dividuum** [comment]
Make sure that you set the environment variable INFOBEAMER_ADDR=0.0.0.0 if you're trying to reach info-beamer from a remote maschine. Otherwise both udp and tcp only allow connections from localhost. Also make sure that packets reach info-beamer. Set INFOBEAMER_LOG_LEVEL=4 and look for "udp packet" lines. If both of these hints don't help, please elaborate what you're doing.

**Comment by deadbutalive** [comment]
victory! thanks

**Comment by dividuum** [comment]
I'll update the documentation to make it clear that you have to do that. Thanks for your report.
